root = "."
testdata_dir = "testdata"
tmp_dir = ".air"

[build]
stop_on_error = true
bin = "./.air/main"
cmd = "go build -o ./.air/main ./src"
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_regex = ["_test.go"]